# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HeadyMovieDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'Kingfisher', '~> 4.0'
    pod 'Swinject', '~> 2.4.1'
    pod 'SwinjectStoryboard', '~> 2.0.2'
    pod 'Alamofire', '~> 4.7.2'
end
